/**
 * Walks `skills/[N]-[category]/[slug]/SKILL.md` and writes a markdown tree
 * into `skills/README.md` between the TREE:START / TREE:END markers.
 *
 * Run: `npm run build-tree` (from scripts/). The ingest workflow runs this
 * automatically after every push to skills/**.
 */

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const SKILLS_DIR = join(REPO_ROOT, 'skills');
const README = join(SKILLS_DIR, 'README.md');

const START = '<!-- TREE:START — auto-generated by scripts/build-taxonomy-tree.ts, do not edit -->';
const END = '<!-- TREE:END -->';

type Skill = { slug: string; description: string };
type Category = { dir: string; num: string; key: string; skills: Skill[] };

function listDirs(path: string): string[] {
  return readdirSync(path)
    .filter(name => statSync(join(path, name)).isDirectory())
    .sort();
}

function readSkill(skillDir: string, slug: string): Skill {
  const skillMd = join(skillDir, 'SKILL.md');
  if (!existsSync(skillMd)) return { slug, description: '_Missing SKILL.md_' };
  try {
    const { data } = matter(readFileSync(skillMd, 'utf-8'));
    const desc = (data?.description ?? '').toString().trim();
    return { slug, description: desc || '_No description_' };
  } catch {
    return { slug, description: '_Unreadable frontmatter_' };
  }
}

function truncate(s: string, max = 140): string {
  const flat = s.replace(/\s+/g, ' ').trim();
  return flat.length > max ? flat.slice(0, max - 1).trimEnd() + '…' : flat;
}

function collect(): Category[] {
  return listDirs(SKILLS_DIR)
    .filter(name => /^\d+-/.test(name))
    .map(dir => {
      const [num, ...rest] = dir.split('-');
      const key = rest.join('-');
      const skills = listDirs(join(SKILLS_DIR, dir)).map(slug =>
        readSkill(join(SKILLS_DIR, dir, slug), slug)
      );
      return { dir, num, key, skills };
    });
}

function render(categories: Category[]): string {
  const total = categories.reduce((n, c) => n + c.skills.length, 0);
  const populated = categories.filter(c => c.skills.length > 0).length;

  const lines: string[] = [];
  lines.push(`_${total} skills across ${categories.length} categories (${populated} populated)._`);
  lines.push('');

  for (const cat of categories) {
    lines.push(`### ${cat.num} · ${cat.key}`);
    if (cat.skills.length === 0) {
      lines.push('');
      lines.push('_No skills yet._');
      lines.push('');
      continue;
    }
    lines.push('');
    for (const s of cat.skills) {
      lines.push(`- **[${s.slug}](${cat.dir}/${s.slug}/SKILL.md)** — ${truncate(s.description)}`);
    }
    lines.push('');
  }

  return lines.join('\n').trimEnd() + '\n';
}

function splice(readme: string, body: string): string {
  const startIdx = readme.indexOf(START);
  const endIdx = readme.indexOf(END);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    throw new Error(
      `Markers not found in ${README}. Add this section to the README first:\n\n## Skill tree\n\n${START}\n${END}\n`
    );
  }
  const before = readme.slice(0, startIdx + START.length);
  const after = readme.slice(endIdx);
  return `${before}\n\n${body}\n${after}`;
}

function main() {
  const categories = collect();
  const body = render(categories);
  const current = readFileSync(README, 'utf-8');
  const next = splice(current, body);
  if (next === current) {
    console.log('Taxonomy tree unchanged.');
    return;
  }
  writeFileSync(README, next, 'utf-8');
  console.log(
    `Updated ${README} — ${categories.length} categories, ${categories.reduce((n, c) => n + c.skills.length, 0)} skills.`
  );
}

main();
